// Generated by https://quicktype.io

class ActorModel {
  int? id;
  String? knownForDepartment;
  String? name;
  String? originalName;
  String? profilePath;
  int? castId;
  String? character;
  int? order;

  ActorModel({
    this.id,
    this.knownForDepartment,
    this.name,
    this.originalName,
    this.profilePath,
    this.castId,
    this.character,
    this.order,
  });

  factory ActorModel.fromMap(Map<String, dynamic> actor) {
    return ActorModel(
      id: actor['id'],
      knownForDepartment: actor['known_for_department'],
      name: actor['name'],
      originalName: actor['original_name'],
      profilePath: actor['profile_path'],
      castId: actor['cast_id'],
      character: actor['character'],
      order: actor['order'],
    );
  }
}
